#!/usr/bin/env sh

echo "php bin/magento setup:upgrade"
#php bin/magento setup:upgrade
echo "-----------------------------"
echo "php bin/magento cache:clean"
php bin/magento cache:clean
echo "-----------------------------"
echo "php bin/magento indexer:reindex"
#php bin/magento indexer:reindex
echo "-----------------------------"
echo "php bin/magento cache:flush"
#php bin/magento cache:flush
echo "-----------------------------"


