<div id="m2-component" data-bind="scope:'m2kocomponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#m2-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "m2kocomponent": {
                        "component": "BodenkoVV_HomeWork10/js/m2kocomponent",
                        "template" : "BodenkoVV_HomeWork10/m2kocomponent-template",
                        "askQuestionTitle" : "<?= $block->escapeHtml(__($block->getAskQuestionTitle())) ?>",
                        "askQuestionText" : "<?= $block->escapeHtml(__($block->getAskQuestionText())) ?>"
                    }
                }
            }
        }
    }
    </script>
</div>
